"""Add verification_sent_at column

Revision ID: b88348f7b04a
Revises: 2fe975d93c40
Create Date: 2026-07-01 23:48:49.327850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88348f7b04a'
down_revision: Union[str, None] = '2fe975d93c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_sent_at')
    # ### end Alembic commands ###
