package com.blesense.app.repository

import com.blesense.app.model.DataLoggerConfig

object DataLoggerRepository {
    val loggers = listOf(
        DataLoggerConfig(
            id = "dl1",
            name = "DataLogger 1",
            advertiserAddress = "DE:AD:BE:AF:AA:11",
            deviceId = "11",
            getDataCommand = byteArrayOf(0xBB.toByte(), 0xCC.toByte()),
            resetCommand = byteArrayOf(0xFF.toByte(), 0xFF.toByte()),
        ),
        DataLoggerConfig(
            id = "dl2",
            name = "DataLogger 2",
            advertiserAddress = "DE:AD:BE:AF:AA:12",
            deviceId = "12",
            getDataCommand = byteArrayOf(0xBC.toByte(), 0xCD.toByte()),
            resetCommand = byteArrayOf(0xFE.toByte(), 0xFF.toByte()),
        ),
        DataLoggerConfig(
            id = "dl3",
            name = "DataLogger 3",
            advertiserAddress = "DE:AD:BE:AF:AA:13",
            deviceId = "13",
            getDataCommand = byteArrayOf(0xBD.toByte(), 0xCE.toByte()),
            resetCommand = byteArrayOf(0xFD.toByte(), 0xFF.toByte()),
        ),
        DataLoggerConfig(
            id = "dl4",
            name = "DataLogger 4",
            advertiserAddress = "DE:AD:BE:AF:AA:14",
            deviceId = "14",
            getDataCommand = byteArrayOf(0xBE.toByte(), 0xCF.toByte()),
            resetCommand = byteArrayOf(0xFC.toByte(), 0xFF.toByte()),
        ),
        DataLoggerConfig(
            id = "dl5",
            name = "DataLogger 5",
            advertiserAddress = "DE:AD:BE:AF:AA:15",
            deviceId = "15",
            getDataCommand = byteArrayOf(0xBF.toByte(), 0xD0.toByte()),
            resetCommand = byteArrayOf(0xFB.toByte(), 0xFF.toByte()),
        ),
        DataLoggerConfig(
            id = "dl6",
            name = "DataLogger 6",
            advertiserAddress = "DE:AD:BE:AF:AA:16",
            deviceId = "16",
            getDataCommand = byteArrayOf(0xC0.toByte(), 0xD1.toByte()),
            resetCommand = byteArrayOf(0xFA.toByte(), 0xFE.toByte()),
        ),
        DataLoggerConfig(
            id = "dl7",
            name = "DataLogger 7",
            advertiserAddress = "DE:AD:BE:AF:AA:17",
            deviceId = "17",
            getDataCommand = byteArrayOf(0xC1.toByte(), 0xD2.toByte()),
            resetCommand = byteArrayOf(0xF9.toByte(), 0xFE.toByte()),
        ),
        DataLoggerConfig(
            id = "dl8",
            name = "DataLogger 8",
            advertiserAddress = "DE:AD:BE:AF:AA:18",
            deviceId = "18",
            getDataCommand = byteArrayOf(0xC2.toByte(), 0xD3.toByte()),
            resetCommand = byteArrayOf(0xF8.toByte(), 0xFE.toByte()),
        ),
        DataLoggerConfig(
            id = "dl9",
            name = "DataLogger 9",
            advertiserAddress = "DE:AD:BE:AF:AA:19",
            deviceId = "19",
            getDataCommand = byteArrayOf(0xC3.toByte(), 0xD4.toByte()),
            resetCommand = byteArrayOf(0xF7.toByte(), 0xFE.toByte()),
        ),
        DataLoggerConfig(
            id = "dl10",
            name = "DataLogger 10",
            advertiserAddress = "DE:AD:BE:AF:AA:20",
            deviceId = "20",
            getDataCommand = byteArrayOf(0xC4.toByte(), 0xD5.toByte()),
            resetCommand = byteArrayOf(0xF6.toByte(), 0xFE.toByte()),
        ),
        DataLoggerConfig(
            id = "dl11",
            name = "DataLogger 11",
            advertiserAddress = "DE:AD:BE:AF:AA:21",
            deviceId = "21",
            getDataCommand = byteArrayOf(0xC5.toByte(), 0xD6.toByte()),
            resetCommand = byteArrayOf(0xF5.toByte(), 0xFD.toByte()),
        ),
        DataLoggerConfig(
            id = "dl12",
            name = "DataLogger 12",
            advertiserAddress = "DE:AD:BE:AF:AA:22",
            deviceId = "22",
            getDataCommand = byteArrayOf(0xC6.toByte(), 0xD7.toByte()),
            resetCommand = byteArrayOf(0xF4.toByte(), 0xFD.toByte()),
        ),
        DataLoggerConfig(
            id = "dl13",
            name = "DataLogger 13",
            advertiserAddress = "DE:AD:BE:AF:AA:23",
            deviceId = "23",
            getDataCommand = byteArrayOf(0xC7.toByte(), 0xD8.toByte()),
            resetCommand = byteArrayOf(0xF3.toByte(), 0xFD.toByte()),
        ),
        DataLoggerConfig(
            id = "dl14",
            name = "DataLogger 14",
            advertiserAddress = "DE:AD:BE:AF:AA:24",
            deviceId = "24",
            getDataCommand = byteArrayOf(0xC8.toByte(), 0xD9.toByte()),
            resetCommand = byteArrayOf(0xF2.toByte(), 0xFD.toByte()),
        ),
        DataLoggerConfig(
            id = "dl15",
            name = "DataLogger 15",
            advertiserAddress = "DE:AD:BE:AF:AA:25",
            deviceId = "25",
            getDataCommand = byteArrayOf(0xC9.toByte(), 0xDA.toByte()),
            resetCommand = byteArrayOf(0xF1.toByte(), 0xFD.toByte()),
        ),
        DataLoggerConfig(
            id = "dl16",
            name = "DataLogger 16",
            advertiserAddress = "DE:AD:BE:AF:AA:26",
            deviceId = "26",
            getDataCommand = byteArrayOf(0xCA.toByte(), 0xDB.toByte()),
            resetCommand = byteArrayOf(0xF0.toByte(), 0xFC.toByte()),
        ),
        DataLoggerConfig(
            id = "dl17",
            name = "DataLogger 17",
            advertiserAddress = "DE:AD:BE:AF:AA:27",
            deviceId = "27",
            getDataCommand = byteArrayOf(0xCB.toByte(), 0xDC.toByte()),
            resetCommand = byteArrayOf(0xEF.toByte(), 0xFC.toByte()),
        ),
        DataLoggerConfig(
            id = "dl18",
            name = "DataLogger 18",
            advertiserAddress = "DE:AD:BE:AF:AA:28",
            deviceId = "28",
            getDataCommand = byteArrayOf(0xCC.toByte(), 0xDD.toByte()),
            resetCommand = byteArrayOf(0xEE.toByte(), 0xFC.toByte()),
        ),
        DataLoggerConfig(
            id = "dl19",
            name = "DataLogger 19",
            advertiserAddress = "DE:AD:BE:AF:AA:29",
            deviceId = "29",
            getDataCommand = byteArrayOf(0xCD.toByte(), 0xDE.toByte()),
            resetCommand = byteArrayOf(0xED.toByte(), 0xFC.toByte()),
        ),
        DataLoggerConfig(
            id = "dl20",
            name = "DataLogger 20",
            advertiserAddress = "DE:AD:BE:AF:AA:30",
            deviceId = "30",
            getDataCommand = byteArrayOf(0xCE.toByte(), 0xDF.toByte()),
            resetCommand = byteArrayOf(0xEC.toByte(), 0xFC.toByte()),
        ),
        DataLoggerConfig(
            id = "dl21",
            name = "DataLogger 21",
            advertiserAddress = "DE:AD:BE:AF:AA:31",
            deviceId = "31",
            getDataCommand = byteArrayOf(0xCF.toByte(), 0xE0.toByte()),
            resetCommand = byteArrayOf(0xEB.toByte(), 0xFB.toByte()),
        ),
        DataLoggerConfig(
            id = "dl22",
            name = "DataLogger 22",
            advertiserAddress = "DE:AD:BE:AF:AA:32",
            deviceId = "32",
            getDataCommand = byteArrayOf(0xD0.toByte(), 0xE1.toByte()),
            resetCommand = byteArrayOf(0xEA.toByte(), 0xFB.toByte()),
        ),
        DataLoggerConfig(
            id = "dl23",
            name = "DataLogger 23",
            advertiserAddress = "DE:AD:BE:AF:AA:33",
            deviceId = "33",
            getDataCommand = byteArrayOf(0xD1.toByte(), 0xE2.toByte()),
            resetCommand = byteArrayOf(0xE9.toByte(), 0xFB.toByte()),
        ),
        DataLoggerConfig(
            id = "dl24",
            name = "DataLogger 24",
            advertiserAddress = "DE:AD:BE:AF:AA:34",
            deviceId = "34",
            getDataCommand = byteArrayOf(0xD2.toByte(), 0xE3.toByte()),
            resetCommand = byteArrayOf(0xE8.toByte(), 0xFB.toByte()),
        ),
        DataLoggerConfig(
            id = "dl25",
            name = "DataLogger 25",
            advertiserAddress = "DE:AD:BE:AF:AA:35",
            deviceId = "35",
            getDataCommand = byteArrayOf(0xD3.toByte(), 0xE4.toByte()),
            resetCommand = byteArrayOf(0xE7.toByte(), 0xFB.toByte()),
        ),
        DataLoggerConfig(
            id = "dl26",
            name = "DataLogger 26",
            advertiserAddress = "DE:AD:BE:AF:AA:36",
            deviceId = "36",
            getDataCommand = byteArrayOf(0xD4.toByte(), 0xE5.toByte()),
            resetCommand = byteArrayOf(0xE6.toByte(), 0xFA.toByte()),
        ),
        DataLoggerConfig(
            id = "dl27",
            name = "DataLogger 27",
            advertiserAddress = "DE:AD:BE:AF:AA:37",
            deviceId = "37",
            getDataCommand = byteArrayOf(0xD5.toByte(), 0xE6.toByte()),
            resetCommand = byteArrayOf(0xE5.toByte(), 0xFA.toByte()),
        ),
        DataLoggerConfig(
            id = "dl28",
            name = "DataLogger 28",
            advertiserAddress = "DE:AD:BE:AF:AA:38",
            deviceId = "38",
            getDataCommand = byteArrayOf(0xD6.toByte(), 0xE7.toByte()),
            resetCommand = byteArrayOf(0xE4.toByte(), 0xFA.toByte()),
        ),
        DataLoggerConfig(
            id = "dl29",
            name = "DataLogger 29",
            advertiserAddress = "DE:AD:BE:AF:AA:39",
            deviceId = "39",
            getDataCommand = byteArrayOf(0xD7.toByte(), 0xE8.toByte()),
            resetCommand = byteArrayOf(0xE3.toByte(), 0xFA.toByte()),
        ),
        DataLoggerConfig(
            id = "dl30",
            name = "DataLogger 30",
            advertiserAddress = "DE:AD:BE:AF:AA:40",
            deviceId = "40",
            getDataCommand = byteArrayOf(0xD8.toByte(), 0xE9.toByte()),
            resetCommand = byteArrayOf(0xE2.toByte(), 0xFA.toByte()),
        ),
        DataLoggerConfig(
            id = "dl31",
            name = "DataLogger 31",
            advertiserAddress = "DE:AD:BE:AF:AA:41",
            deviceId = "41",
            getDataCommand = byteArrayOf(0xD9.toByte(), 0xEA.toByte()),
            resetCommand = byteArrayOf(0xE1.toByte(), 0xF9.toByte()),
        ),
        DataLoggerConfig(
            id = "dl32",
            name = "DataLogger 32",
            advertiserAddress = "DE:AD:BE:AF:AA:42",
            deviceId = "42",
            getDataCommand = byteArrayOf(0xDA.toByte(), 0xEB.toByte()),
            resetCommand = byteArrayOf(0xE0.toByte(), 0xF9.toByte()),
        ),
        DataLoggerConfig(
            id="dl33",
            name="DataLogger 33",
            advertiserAddress="DE:AD:BE:AF:AA:43",
            deviceId="43",
            getDataCommand=byteArrayOf(0xDB.toByte(),0xEC.toByte()),
            resetCommand=byteArrayOf(0xDF.toByte(),0xF9.toByte()),
        ),
        DataLoggerConfig(
            id="dl34",
            name="DataLogger 34",
            advertiserAddress="DE:AD:BE:AF:AA:44",
            deviceId="44",
            getDataCommand=byteArrayOf(0xDC.toByte(),0xED.toByte()),
            resetCommand=byteArrayOf(0xDE.toByte(),0xF9.toByte()),
        ),
        DataLoggerConfig(
            id="dl35",
            name="DataLogger 35",
            advertiserAddress="DE:AD:BE:AF:AA:45",
            deviceId="45",
            getDataCommand=byteArrayOf(0xDD.toByte(),0xEE.toByte()),
            resetCommand=byteArrayOf(0xDD.toByte(),0xF9.toByte()),
        ),
        DataLoggerConfig(
            id="dl36",
            name="DataLogger 36",
            advertiserAddress="DE:AD:BE:AF:AA:46",
            deviceId="46",
            getDataCommand=byteArrayOf(0xDE.toByte(),0xEF.toByte()),
            resetCommand=byteArrayOf(0xDC.toByte(),0xF8.toByte()),
        ),
        DataLoggerConfig(
            id="dl37",
            name="DataLogger 37",
            advertiserAddress="DE:AD:BE:AF:AA:47",
            deviceId="47",
            getDataCommand=byteArrayOf(0xDF.toByte(),0xF0.toByte()),
            resetCommand=byteArrayOf(0xDB.toByte(),0xF8.toByte()),
        ),
        DataLoggerConfig(
            id="dl38",
            name="DataLogger 38",
            advertiserAddress="DE:AD:BE:AF:AA:48",
            deviceId="48",
            getDataCommand=byteArrayOf(0xE0.toByte(),0xF1.toByte()),
            resetCommand=byteArrayOf(0xDA.toByte(),0xF8.toByte()),
        ),
        DataLoggerConfig(
            id="dl39",
            name="DataLogger 39",
            advertiserAddress="DE:AD:BE:AF:AA:49",
            deviceId="49",
            getDataCommand=byteArrayOf(0xE1.toByte(),0xF2.toByte()),
            resetCommand=byteArrayOf(0xD9.toByte(),0xF8.toByte()),
        ),
        DataLoggerConfig(
            id="dl40",
            name="DataLogger 40",
            advertiserAddress="DE:AD:BE:AF:AA:50",
            deviceId="50",
            getDataCommand=byteArrayOf(0xE2.toByte(),0xF3.toByte()),
            resetCommand=byteArrayOf(0xD8.toByte(),0xF8.toByte()),
        ),
        DataLoggerConfig(
            id="dl41",
            name="DataLogger 41",
            advertiserAddress="DE:AD:BE:AF:AA:51",
            deviceId="51",
            getDataCommand=byteArrayOf(0xE3.toByte(),0xF4.toByte()),
            resetCommand=byteArrayOf(0xD7.toByte(),0xF7.toByte()),
        ),
        DataLoggerConfig(
            id="dl42",
            name="DataLogger 42",
            advertiserAddress="DE:AD:BE:AF:AA:52",
            deviceId="52",
            getDataCommand=byteArrayOf(0xE4.toByte(),0xF5.toByte()),
            resetCommand=byteArrayOf(0xD6.toByte(),0xF7.toByte()),
        ),
        DataLoggerConfig(
            id="dl43",
            name="DataLogger 43",
            advertiserAddress="DE:AD:BE:AF:AA:53",
            deviceId="53",
            getDataCommand=byteArrayOf(0xE5.toByte(),0xF6.toByte()),
            resetCommand=byteArrayOf(0xD5.toByte(),0xF7.toByte()),
        ),
        DataLoggerConfig(
            id="dl44",
            name="DataLogger 44",
            advertiserAddress="DE:AD:BE:AF:AA:54",
            deviceId="54",
            getDataCommand=byteArrayOf(0xE6.toByte(),0xF7.toByte()),
            resetCommand=byteArrayOf(0xD4.toByte(),0xF7.toByte()),
        ),
        DataLoggerConfig(
            id="dl45",
            name="DataLogger 45",
            advertiserAddress="DE:AD:BE:AF:AA:55",
            deviceId="55",
            getDataCommand=byteArrayOf(0xE7.toByte(),0xF8.toByte()),
            resetCommand=byteArrayOf(0xD3.toByte(),0xF7.toByte()),
        ),
        DataLoggerConfig(
            id="dl46",
            name="DataLogger 46",
            advertiserAddress="DE:AD:BE:AF:AA:56",
            deviceId="56",
            getDataCommand=byteArrayOf(0xE8.toByte(),0xF9.toByte()),
            resetCommand=byteArrayOf(0xD2.toByte(),0xF6.toByte()),
        ),
        DataLoggerConfig(
            id="dl47",
            name="DataLogger 47",
            advertiserAddress="DE:AD:BE:AF:AA:57",
            deviceId="57",
            getDataCommand=byteArrayOf(0xE9.toByte(),0xFA.toByte()),
            resetCommand=byteArrayOf(0xD1.toByte(),0xF6.toByte()),
        ),
        DataLoggerConfig(
            id="dl48",
            name="DataLogger 48",
            advertiserAddress="DE:AD:BE:AF:AA:58",
            deviceId="58",
            getDataCommand=byteArrayOf(0xEA.toByte(),0xF1.toByte()),
            resetCommand=byteArrayOf(0xD0.toByte(),0xF6.toByte()),
        ),
        DataLoggerConfig(
            id="dl49",
            name="DataLogger 49",
            advertiserAddress="DE:AD:BE:AF:AA:59",
            deviceId="59",
            getDataCommand=byteArrayOf(0xEB.toByte(),0xFC.toByte()),
            resetCommand=byteArrayOf(0xCF.toByte(),0xF6.toByte()),
        ),
        DataLoggerConfig(
            id="dl50",
            name="DataLogger 50",
            advertiserAddress="DE:AD:BE:AF:AA:60",
            deviceId="60",
            getDataCommand=byteArrayOf(0xEC.toByte(),0xFD.toByte()),
            resetCommand=byteArrayOf(0xCE.toByte(),0xF6.toByte()),
        )
    )

    fun getLoggerById(id: String): DataLoggerConfig? = loggers.find { it.id == id }
    fun getLoggerByAddress(address: String): DataLoggerConfig? = loggers.find { it.advertiserAddress.equals(address, ignoreCase = true) }
    fun getLoggerByDeviceId(deviceId: String): DataLoggerConfig? = loggers.find { it.deviceId == deviceId }
}
