"""Add: Tag Registry

Revision ID: 228e6ee42a3a
Revises: b88348f7b04a
Create Date: 2026-07-03 11:48:35.913729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228e6ee42a3a'
down_revision: Union[str, None] = 'b88348f7b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_registry_device_id'), 'tag_registry', ['device_id'], unique=True)
    op.create_index(op.f('ix_tag_registry_id'), 'tag_registry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_registry_id'), table_name='tag_registry')
    op.drop_index(op.f('ix_tag_registry_device_id'), table_name='tag_registry')
    op.drop_table('tag_registry')
    # ### end Alembic commands ###
