"""Add datalogger ingestion queue models

Revision ID: 2fe975d93c40
Revises: 18bc67ebd5d2
Create Date: 2026-06-11 16:53:13.605123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe975d93c40'
down_revision: Union[str, None] = '18bc67ebd5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_packets_id'), 'raw_packets', ['id'], unique=False)
    op.create_index(op.f('ix_raw_packets_status'), 'raw_packets', ['status'], unique=False)
    op.create_table('sensor_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_packets_app_id'), 'sensor_packets', ['app_id'], unique=False)
    op.create_index(op.f('ix_sensor_packets_id'), 'sensor_packets', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_packets_timestamp'), 'sensor_packets', ['timestamp'], unique=False)
    op.create_table('datalogger_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_packet_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('packet_id_num', sa.Integer(), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['raw_packet_id'], ['raw_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datalogger_headers_app_id'), 'datalogger_headers', ['app_id'], unique=False)
    op.create_index(op.f('ix_datalogger_headers_device_id'), 'datalogger_headers', ['device_id'], unique=False)
    op.create_index(op.f('ix_datalogger_headers_id'), 'datalogger_headers', ['id'], unique=False)
    op.create_table('datalogger_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('z', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['datalogger_headers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datalogger_points_id'), 'datalogger_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datalogger_points_id'), table_name='datalogger_points')
    op.drop_table('datalogger_points')
    op.drop_index(op.f('ix_datalogger_headers_id'), table_name='datalogger_headers')
    op.drop_index(op.f('ix_datalogger_headers_device_id'), table_name='datalogger_headers')
    op.drop_index(op.f('ix_datalogger_headers_app_id'), table_name='datalogger_headers')
    op.drop_table('datalogger_headers')
    op.drop_index(op.f('ix_sensor_packets_timestamp'), table_name='sensor_packets')
    op.drop_index(op.f('ix_sensor_packets_id'), table_name='sensor_packets')
    op.drop_index(op.f('ix_sensor_packets_app_id'), table_name='sensor_packets')
    op.drop_table('sensor_packets')
    op.drop_index(op.f('ix_raw_packets_status'), table_name='raw_packets')
    op.drop_index(op.f('ix_raw_packets_id'), table_name='raw_packets')
    op.drop_table('raw_packets')
    # ### end Alembic commands ###
